# Combined Cycle Power Plant ANN Regression

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf


# Part 1 - Data Preprocessing

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
print(dataset)

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]


In [4]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

In [5]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [6]:
print(Y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

# Part 2 - Building the ANN

## Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the second hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

# Part 3 - Training the ANN

## Compiling the ANN

In [13]:
ann.compile(optimizer='adam', loss='mean_squared_error')

# Training the ANN model on the Training set

In [15]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 492.4434
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 348.3304
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 285.4638
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 223.6802
Epoch 5/100
240/240 [==============================] - 0s 985us/step - loss: 172.0916
Epoch 6/100
240/240 [==============================] - 0s 961us/step - loss: 131.3358
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 99.9280
Epoch 8/100
240/240 [==============================] - 0s 986us/step - loss: 77.4284
Epoch 9/100
240/240 [==============================] - 0s 977us/step - loss: 61.6685
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 50.3223
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 44.3269
Epoch 12/100
240/240 [==============================] - 0s 953us/step -

# Predicting the results of the Test set

In [16]:
y_pred = ann.predict(X_test)
print(y_pred)

[[431.8202 ]
 [460.8834 ]
 [467.0664 ]
 ...
 [473.23358]
 [438.6996 ]
 [458.041  ]]


In [17]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.82 431.23]
 [460.88 460.01]
 [467.07 461.14]
 ...
 [473.23 473.26]
 [438.7  438.  ]
 [458.04 463.28]]


# Prediction using R2 Score

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9206465846927749